/**
 * Config types and helpers for the USRCP browser extension.
 *
 * Written to ~/.usrcp/extension-config.json at mode 0600 by runExtensionSetup.
 */

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ExtensionConfig {
  /** The extension ID generated by Chrome for the unpacked load. */
  extension_id: string;
  /** Absolute path to usrcp-bridge.js on this machine. */
  bridge_path: string;
  /** Path where the Chrome NM manifest was written. */
  manifest_path: string;
  /** ISO timestamp of when setup was run. */
  configured_at: string;
}

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

export function getUsrcpDir(): string {
  return path.join(os.homedir(), ".usrcp");
}

export function getConfigPath(): string {
  return path.join(getUsrcpDir(), "extension-config.json");
}

/**
 * Chrome NM manifest path on macOS.
 * Linux variant: ~/.config/google-chrome/NativeMessagingHosts/
 * (v0 supports macOS only; Linux noted for v0.1)
 */
export function getNMManifestPath(): string {
  if (process.platform === "darwin") {
    return path.join(
      os.homedir(),
      "Library",
      "Application Support",
      "Google",
      "Chrome",
      "NativeMessagingHosts",
      "com.usrcp.bridge.json"
    );
  }
  if (process.platform === "linux") {
    return path.join(
      os.homedir(),
      ".config",
      "google-chrome",
      "NativeMessagingHosts",
      "com.usrcp.bridge.json"
    );
  }
  // Windows: requires a registry key. Not implemented in v0.
  throw new Error(
    "Windows NM manifest installation is not implemented in v0. " +
    "See README for manual instructions."
  );
}

// ---------------------------------------------------------------------------
// Read / write
// ---------------------------------------------------------------------------

export function writeExtensionConfig(cfg: ExtensionConfig): void {
  const dir = getUsrcpDir();
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  }
  const configPath = getConfigPath();
  fs.writeFileSync(configPath, JSON.stringify(cfg, null, 2) + "\n", {
    encoding: "utf8",
    mode: 0o600,
    flag: "w",
  });
}

export function loadExtensionConfig(): ExtensionConfig {
  const configPath = getConfigPath();
  if (!fs.existsSync(configPath)) {
    throw new Error(
      `Extension config not found at ${configPath}. ` +
      "Run 'usrcp setup --adapter=extension' first."
    );
  }
  const raw = fs.readFileSync(configPath, "utf8");
  return JSON.parse(raw) as ExtensionConfig;
}
