/**
 * Config types and helpers for the USRCP browser extension.
 *
 * Written to ~/.usrcp/extension-config.json at mode 0600 by runExtensionSetup.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { requireHomeDir } from "usrcp-core/encryption";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ExtensionConfig {
  /** The extension ID generated by Chrome for the unpacked load. */
  extension_id: string;
  /** Absolute path to usrcp-bridge.cjs on this machine. */
  bridge_path: string;
  /** Absolute path to the pinned-Node launcher registered with Chrome. */
  native_host_path?: string;
  /** Absolute path to the Node executable pinned by native_host_path. */
  node_path?: string;
  /** Path where the Chrome NM manifest was written. */
  manifest_path: string;
  /** ISO timestamp of when setup was run. */
  configured_at: string;
  /**
   * Domains the extension is authorized to search via `/usrcp <query>`.
   * SECURITY (v0.1.3+): the bridge requires this to be a non-empty
   * array — if empty / undefined, memory.search returns no results.
   * Defense-in-depth: even if page JS finds a way around the
   * content-script HMAC boundary, the bridge only ever
   * surfaces snippets from these specific domains, never the whole
   * ledger. The setup wizard prompts for this; legacy configs
   * without the field fail closed with a clear error.
   */
  allowed_domains?: string[];
}

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

export function getUsrcpDir(): string {
  // requireHomeDir(), not os.homedir(): an empty HOME would make this a
  // relative ".usrcp" and the extension config / native-host launcher would
  // be written into the CWD (#192, same class as #174/#183). Every path in
  // this file funnels through here or getNMManifestPath below.
  return path.join(requireHomeDir(), ".usrcp");
}

export function getConfigPath(): string {
  return path.join(getUsrcpDir(), "extension-config.json");
}

export function getNativeHostLauncherPath(): string {
  return path.join(getUsrcpDir(), "native-host", "usrcp-extension-bridge.sh");
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\"'\"'`)}'`;
}

export function writeNativeHostLauncher(nodePath: string, bridgePath: string): string {
  if (!path.isAbsolute(nodePath) || !path.isAbsolute(bridgePath)) {
    throw new Error("Native host launcher requires absolute Node and bridge paths.");
  }

  const launcherPath = getNativeHostLauncherPath();
  fs.mkdirSync(path.dirname(launcherPath), { recursive: true, mode: 0o700 });
  fs.writeFileSync(
    launcherPath,
    `#!/bin/sh\nexec ${shellQuote(nodePath)} ${shellQuote(bridgePath)} \"$@\"\n`,
    { encoding: "utf8", mode: 0o700, flag: "w" }
  );
  fs.chmodSync(launcherPath, 0o700);
  return launcherPath;
}

/**
 * Chrome NM manifest path on macOS.
 * Linux variant: ~/.config/google-chrome/NativeMessagingHosts/
 * (v0 supports macOS only; Linux noted for v0.1)
 */
export function getNMManifestPath(): string {
  // requireHomeDir(), not os.homedir(): under empty HOME the Chrome native-
  // messaging manifest would be written to a relative path in the CWD (#192).
  const home = requireHomeDir();
  if (process.platform === "darwin") {
    return path.join(
      home,
      "Library",
      "Application Support",
      "Google",
      "Chrome",
      "NativeMessagingHosts",
      "com.usrcp.bridge.json"
    );
  }
  if (process.platform === "linux") {
    return path.join(
      home,
      ".config",
      "google-chrome",
      "NativeMessagingHosts",
      "com.usrcp.bridge.json"
    );
  }
  // Windows: requires a registry key. Not implemented in v0.
  throw new Error(
    "Windows NM manifest installation is not implemented in v0. " +
    "See README for manual instructions."
  );
}

// ---------------------------------------------------------------------------
// Read / write
// ---------------------------------------------------------------------------

export function writeExtensionConfig(cfg: ExtensionConfig): void {
  const dir = getUsrcpDir();
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  }
  const configPath = getConfigPath();
  fs.writeFileSync(configPath, JSON.stringify(cfg, null, 2) + "\n", {
    encoding: "utf8",
    mode: 0o600,
    flag: "w",
  });
}

export function loadExtensionConfig(): ExtensionConfig {
  const configPath = getConfigPath();
  if (!fs.existsSync(configPath)) {
    throw new Error(
      `Extension config not found at ${configPath}. ` +
      "Run 'usrcp setup --adapter=extension' first."
    );
  }
  const raw = fs.readFileSync(configPath, "utf8");
  return JSON.parse(raw) as ExtensionConfig;
}
