/**
 * CONTEXT.md generator — reads recent ledger events and writes a markdown
 * summary to ~/.usrcp/CONTEXT.md.
 *
 * Called by `usrcp adapter terminal refresh-context`. Designed to be
 * safe to run frequently (e.g., every 15 minutes via cron). The cron
 * entry itself is NOT installed here — the setup wizard does that.
 *
 * The resulting CONTEXT.md gives Aider (and any other tool that reads it)
 * a warm-start context summary of recent USRCP activity without requiring
 * an MCP tool call.
 */

import { promises as fs } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { Ledger } from "../../ledger/index.js";
import {
  isPassphraseMode,
  migrateLegacyLayout,
  listUserSlugs,
  setUserSlug,
} from "../../encryption.js";

const DEFAULT_LAST_N = 50;

function outputPath(): string {
  return join(homedir(), ".usrcp", "CONTEXT.md");
}

function formatEvent(ev: {
  timestamp: string;
  platform: string;
  domain: string;
  summary: string;
  intent?: string;
  outcome?: string;
}): string {
  const date = ev.timestamp.slice(0, 10);
  const outcome = ev.outcome ? ` [${ev.outcome}]` : "";
  const intent = ev.intent ? ` — intent: ${ev.intent}` : "";
  return `- **${date}** [${ev.platform}/${ev.domain}]${outcome}: ${ev.summary}${intent}`;
}

export async function refreshContextMd(opts: {
  lastN?: number;
  passphrase?: string;
  userSlug?: string;
} = {}): Promise<string> {
  migrateLegacyLayout();

  const slugs = listUserSlugs();
  const slug = opts.userSlug ?? (slugs.length === 1 ? slugs[0] : "default");
  setUserSlug(slug);

  const passphrase = opts.passphrase;
  const ledger = new Ledger(undefined, passphrase);
  const events = ledger.getTimeline({ last_n: opts.lastN ?? DEFAULT_LAST_N });
  const stats = ledger.getStats();
  ledger.close();

  const now = new Date().toISOString();
  const lines: string[] = [
    `# USRCP Context — ${now}`,
    "",
    `> Auto-generated by \`usrcp adapter terminal refresh-context\`. Do not edit.`,
    `> User: ${slug} | Events: ${stats.total_events} | Platforms: ${stats.platforms.join(", ") || "(none)"}`,
    "",
    `## Recent activity (last ${events.length})`,
    "",
  ];

  if (events.length === 0) {
    lines.push("_(no events yet)_");
  } else {
    for (const ev of events) {
      lines.push(formatEvent(ev));
    }
  }

  const content = lines.join("\n") + "\n";
  await fs.mkdir(join(homedir(), ".usrcp"), { recursive: true });
  const output = outputPath();
  await fs.writeFile(output, content, { mode: 0o600 });
  return output;
}
